openapi: 3.0.0
info:
  title: firstopenAPI
  description: firstAPI Description
  version: 1.0.0
#  contact:
#    name: kunal
#    url: https://www.youtube.com
#    email: mailto:kunal@gmail.com
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: ok
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/course'


  /addCourses:
    post:
      description: to store courses
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/toaddcourse'
        description: course uploaded sucessfully
      responses:
        '200':
          description: upload sucessfull





components:
  schemas:
    course:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        id:
          type: integer



    toaddcourse:
      type: object
      properties:
        nameOfCourse:
          type: string
        aboutCourse:
          type: string
        course_id:
          type: integer





